# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: whodoesntlovereddit

frameworkVersion: "2"
# projectDir: ./

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  memorySize: 256
  region: ap-south-1
  stage: ${opt:stage, 'dev'}
  profile: whodoesntlovereddit
  environment:
    DAILY_UPLOADS_TABLE_NAME: ${self:custom.DailyUploadsTable.name}
    REDDIT_ACCOUNTS_TABLE_NAME: ${self:custom.RedditAccountsTable.name}
    REDDIT_AUTH_URL: 'https://www.reddit.com/api/v1/access_token'
    REDDIT_API_URL_TOP: 'https://oauth.reddit.com/r/placeholder_value/top'
    GATHER_URLS_FOR_A_SUBREDDIT_QUEUE_URL: ${self:custom.GatherUrlsForASubredditQueue.name}  
    PROCESS_URLS_FOR_SUBREDDIT_GROUP_QUEUE_URL: ${self:custom.ProcessUrlsForSubredditGroupQueue.name}  

  ecr:
    images:
      firstImage:
        path: lambdas/first_lambda_container/

      daily_uploads_gather_urls_image:
        path: images/

plugins:
  - serverless-iam-roles-per-function

package:
  individually: true
  patterns:
    - '!.venv/**'
    - '!node_modules/**'
    - '!scripts/**'
    - 'lib/'    
    - '!README.txt'
    - '!copy_tree.py'
    - '!**/*.ipynb'
    # - 'lambdas/check_for_new_subreddits/subredditList.py'

resources:
  Resources:
    VideoUrlsTable: ${file(resources/Tables/VideoUrlsTable.yml):VideoUrlsTable}
    DailyUploadsTable: ${file(resources/Tables/DailyUploadsTable.yml):DailyUploadsTable}
    RedditAccountsTable: ${file(resources/Tables/RedditAccountsTable.yml):RedditAccountsTable}
    GatherUrlsForASubredditQueue: ${file(resources/Queues/GatherUrlsForASubreddit.yml):resource}
    ProcessUrlsForSubredditGroupQueue: ${file(resources/Queues/ProcessUrlsForSubredditGroup.yml):resource}

custom:
  DailyUploadsTable:
    name: !Ref DailyUploadsTable
    arn: !GetAtt DailyUploadsTable.Arn

  VideoUrlsTable:
    name: !Ref VideoUrlsTable
    arn: !GetAtt VideoUrlsTable.Arn

  RedditAccountsTable:
    name: !Ref RedditAccountsTable
    arn: !GetAtt RedditAccountsTable.Arn

  GatherUrlsForASubredditQueue:
    name: !Ref GatherUrlsForASubredditQueue
    arn: !GetAtt GatherUrlsForASubredditQueue.Arn

  ProcessUrlsForSubredditGroupQueue:
    name: !Ref ProcessUrlsForSubredditGroupQueue
    arn: !GetAtt ProcessUrlsForSubredditGroupQueue.Arn

functions:
  - update_db_wakeup_ec2s: ${file(lambdas/update_db_wakeup_ec2s/generic.yml):function}
  - check_for_new_subreddits_and_push_to_sqs: ${file(lambdas/check_for_new_subreddits_and_push_to_sqs/generic.yml):function}
  - pick_from_sqs_and_preprocess: ${file(lambdas/pick_from_sqs_and_preprocess/generic.yml):function}
  - first_lambda_container: ${file(lambdas/first_lambda_container/generic.yml):function}
  - daily_uploads_gather_urls: ${file(lambdas/daily_uploads/gather_urls/generic.yml):function}

 
