# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: whodoesntlovereddit

frameworkVersion: "2"
projectDir: ./

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  memorySize: 256
  region: ap-south-1
  stage: ${opt:stage, 'dev'}
  profile: whodoesntlovereddit
  ecr:
    images:
      firstImage:
        path: lambdas/first_lambda_container/

plugins:
  - serverless-iam-roles-per-function
  # - serverless-python-requirements

package:
  individually: true
  patterns:
    - '!.venv/**'
    - '!node_modules/**'
    - '!scripts/**'
    # - 'lambdas/check_for_new_subreddits/subredditList.py'

resources:
  Resources:
    VideoUrlsTable: ${file(resources/Tables/VideoUrlsTable.yml):VideoUrlsTable}
    RedditAccountsTable: ${file(resources/Tables/RedditAccountsTable.yml):RedditAccountsTable}
    InitialSubredditQueue: ${file(resources/Queues/InitialSubredditQueue.yml):InitialSubredditQueue}

custom:
  VideoUrlsTable:
    name: !Ref VideoUrlsTable
    arn: !GetAtt VideoUrlsTable.Arn
  RedditAccountsTable:
    name: !Ref RedditAccountsTable
    arn: !GetAtt RedditAccountsTable.Arn
  InitialSubredditQueue:
    name: !Ref InitialSubredditQueue
    arn: !GetAtt InitialSubredditQueue.Arn
  
    

functions:
  - update_db_wakeup_ec2s: ${file(lambdas/update_db_wakeup_ec2s/generic.yml):function}
  - check_for_new_subreddits_and_push_to_sqs: ${file(lambdas/check_for_new_subreddits_and_push_to_sqs/generic.yml):function}
  - pick_from_sqs_and_preprocess: ${file(lambdas/pick_from_sqs_and_preprocess/generic.yml):function}
  - first_lambda_container: ${file(lambdas/first_lambda_container/generic.yml):function}

 
