subreddit_groups = [
    [
        "nonononoyes",
        "HolUp",
        "yesyesyesyesno",
        "therewasanattempt",
        "killedthecameraman",
        "killthecameraman",
        "PraiseTheCameraMan",
        "nevertellmetheodds",
    ],
    [
        "PeopleBeingJerks",
        "PeopleFuckingDying",
        "peopleofwalmart",
        "WatchPeopleDieInside",
        "ChildrenFallingOver",
        "thisismylifenow",
        "KidsAreFuckingStupid",
    ],
    [
        "holdmybeer",
        "holdmyfries",
        "holdmyjuicebox",
        "holdmycosmo",
        "holdmyredbull",
        "holdmyfeedingtube",
        "FullScorpion",
        "therewasanattempt",
        "Whatcouldgowrong",
        "meatcrayon",
        "WinStupidPrizes",
        "FatPeopleFalling",
    ],
    # [
    #     "Unexpected",
    #     "BeAmazed",
    #     "interestingasfuck",
    #     "EngineeringPorn",
    #     "holdmyredbull",
    #     "theydidthemath",
    #     "ThatsInsane",
    #     "HumansAreMetal",
    #     "watchpeoplesurvive",
    #     "Damnthatsinteresting",
    #     "youseeingthisshit",
    #     "nonononoyes",
    #     "WTF",
    # ],
    # [
    #     "Idiotswithguns",
    #     "IdiotsNearlyDying",
    #     "IdiotsInCars",
    #     "IdiotsFightingThings",
    #     "IdiotsInBoats",
    #     "fightporn",
    #     "WhyWomenLiveLonger",
    #     "facepalm",
    #     "ufc",
    #     "Prematurecelebration",
    #     "worstaccidents",
    #     "instantkarma",
    #     "instant_regret",
    #     "Instantregret",
    #     "watchpeoplesurvive",
    #     "ConvenientCop",
    #     "JusticeServed",
    #     "ThatLookedExpensive",
    #     "Whatcouldgowrong",
    # ],
    [
        "normaldayinrussia",
        "NormalDayInArabia",
        "funny",
        "funnyvideos",
        "ItHadToBeBrazil",
        "AbruptChaos",
        "instantbarbarians",
        "ContagiousLaughter",
        "OneSecondBeforeDisast",
        "woahdude",
        "AbsoluteUnits",
        "memes",
        "Dank",
        "dankmemes",
        "KidsAreFuckingEvil",
        "KidsAreFuckingStupid",
        "KidsAreFuckingSmart",
        "MyPeopleNeedMe",
    ],
    # [
    #     "mildyinfuriating",
    #     "bizarrelife",
    #     "AnimalsBeingDerps",
    #     "AnimalsBeingJerks",
    #     "maybemaybemaybe",
    #     "Wellthatsucks",
    #     "WinStupidPrizes",
    #     "WhyWereTheyFilming",
    #     "perfectlycutscreams",
    #     "CrazyFuckingVideos",
    #     "HeavySeas",
    # ],
    [
        "HumansAreMetal",
        "aviation",
        "toptalent",
        "specializedtools",
        "HumansForScale",
        "nextfuckinglevel",
        "ballsthatclank",
        "JusticeServed",
        "NatureIsFuckingLit",
        "youseeingthisshit",
        "BeAmazed",
    ],
    # [
    #     "theydidthemath",
    #     "Damnthatsinteresting",
    #     "BadChoicesGoodStories",
    #     "ThatsInsane",
    #     "JustGuysBeingDudes",
    #     "GirlsInaGif",
    #     "lifehacks",
    #     "aviation",
    #     "instantbarbarians",
    # ],
    [
        "oddlysatisfying",
        "aviation",
        "Eyebleach",
        "specializedtools",
        "powerwashingporn",
        "mechanical_gifs",
        "ManufacturingPorn",
        "EngineeringPorn",
        "ContagiousLaughter",
        "woodworking",
        "Satisfyingasfuck",
        "DadReflexes",
        "perfectloops",
        "BetterEveryLoop",
        "Perfectfit",
        "PerfectTiming",
        "mildlysatisfying",
        "dataisbeautiful",
        "InternetIsBeautiful",
        "BeAmazed",
        "awesome",
        "watchpeoplesurvive",
        "lifehacks",
        "ScienceNcoolThings",
    ],
    # [
    #     "DudeFuckThat",
    #     "SweatyPalms",
    #     "CatastrophicFailure",
    #     "oddlyterrifying",
    #     "donthelpjustfilm",
    #     "WinStupidPrizes",
    # ],
    [
        "wholesomegifs",
        "MadeMeSmile",
        "Eyebleach",
        "wholesomememes",
        "HumansBeingBros",
        "AnimalsBeingBros",
        "AnimalsBeingGeniuses",
        "happycrowds",
        "happycryingdads",
        "happycowgifs",
        "dogswithjobs",
        "bigboye",
        "MasterReturns",
        "badassanimals",
        "ALLTHEANIMALS",
        "DadReflexes",
    ],
    # [
    #     "aww",
    #     "Awwducational",
    #     "Awww",
    #     "WorldsCutest",
    #     "NoisyCats",
    #     "animalssmiling",
    #     "dogswithjobs",
    #     "PraiseTheCameraDog",
    #     "Zoomies",
    #     "Waterdogs",
    #     "WhatsWrongWithYourDog",
    #     "WhatsWrongWithYourCat",
    #     "AnimalsBeingDerps",
    #     "AnimalsBeingBros",
    #     "animalsdoingstuff",
    #     "woof_irl",
    #     "PetTheDamnDog",
    #     "Catculations",
    #     "HappyPitbull",
    #     "StoppedWorking",
    #     "StartledCats",
    #     "MasterReturns",
    #     "bigboye",
    #     "Kitten",
    #     "happycowgifs",
    #     "tippytaps",
    #     "hitmanimals",
    #     "badassanimals",
    #     "ALLTHEANIMALS",
    #     "ClumsyAnimals",
    #     "Chonkers",
    #     "AnimalTextGifs",
    #     "bearsdoinghumanthings",
    # ],
]
