VideoUrlsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: VideoUrlsTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      # Naming the Date as the PK to easily identify. 
      # Will have Date as the Partition Key.
      - AttributeName: PK # Holds the date in  the format:  yyyy:mmmm:dd
        AttributeType: S
        
      # Naming the subreddit name as the sort key
      # Will be used to gather urls for that subreddit
      - AttributeName: SK # Holds the subreddit name 
        AttributeType: S
    KeySchema:
      - AttributeName: PK
        KeyType: HASH
      - AttributeName: "SK"
        KeyType: "RANGE"
