RedditAccountsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: RedditAccountsTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: PK
        AttributeType: S
      # - AttributeName: email_address
      #   AttributeType: S
    KeySchema:
      - AttributeName: PK
        KeyType: HASH
      # - AttributeName: email_address
      #   KeyType: RANGE
