RedditAccountsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: RedditAccountsTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: subreddit
        AttributeType: S
      - AttributeName: email_address
        AttributeType: S
    KeySchema:
      - AttributeName: subreddit
        KeyType: HASH
      - AttributeName: email_address
        KeyType: RANGE
