VideoUrlsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: VideoUrlsTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: PK # Holds the date in  the format:  yyyy:mmmm:dd
        AttributeType: S

      - AttributeName: SK
        AttributeType: S

    KeySchema:
      - AttributeName: PK
        KeyType: HASH

      - AttributeName: SK
        KeyType: RANGE

    TimeToLiveSpecification:
      AttributeName: "TTL"
      Enabled: true
