VideoUrlsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: VideoUrlsTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: url
        AttributeType: S

      # - AttributeName: status
      #   AttributeType: S
      # # ISO strings are represented as strings.
      # - AttributeName: endingAt
      #   AttributeType: S
    KeySchema:
      - AttributeName: url
        KeyType: HASH
    # GlobalSecondaryIndexes:
    #   - IndexName: statusAndEndDate
    #     KeySchema:
    #       - AttributeName: status
    #         KeyType: HASH
    #       - AttributeName: endingAt
    #         KeyType: RANGE
    #     Projection:
    #       ProjectionType: ALL
