VideoUrlsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: VideoUrlsTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: PK # Holds the subreddits_group delimited by - and date
        AttributeType: S

      - AttributeName: SK # Holds the post url
        AttributeType: S

    KeySchema:
      - AttributeName: PK
        KeyType: HASH

      - AttributeName: SK
        KeyType: RANGE

    TimeToLiveSpecification:
      AttributeName: "TTL"
      Enabled: true
